{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "certstream-server-go.serviceAccountName" . }}
  labels:
    {{- include "certstream-server-go.labels" . | nindent 4 }}
{{- end }}