apiVersion: v1
kind: Service
metadata:
  name: {{ include "certstream-server-go.fullname" . }}
  labels:
    {{- include "certstream-server-go.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.webserver.listen_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.config.prometheus.listen_port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "certstream-server-go.selectorLabels" . | nindent 4 }}