apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certstream-server-go
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/x123/certstream-server-go.git'
    targetRevision: HEAD
    path: k8s/charts/certstream-server-go
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: certstream
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
